In [2]:
import numpy as np

In [7]:
a1 = np.array([1,2,3])
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2])
a1[0] = -1
print(a1[0], a1[1], a1[2])



<class 'numpy.ndarray'>
(3,)
1 2 3
-1 2 3


In [11]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a2))
print(a2.shape)
print(a2[0,0])

<class 'numpy.ndarray'>
(3, 3)
1


In [16]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(type(a3))
print(a3.shape)
print(a3[0,0,0])

<class 'numpy.ndarray'>
(3, 3, 3)
1


In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [21]:
np.eye(3)  # 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])